import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const siteRoot = resolve('dist/site');
const pages = ['index.html', 'privacy/index.html', 'terms/index.html'];
const html = await Promise.all(pages.map((page) => readFile(resolve(siteRoot, page), 'utf8')));
const assets = [...new Set(
  html.flatMap((page) => [...page.matchAll(/(?:src|href)="(\/assets\/[^"\s]+)"/g)].map((match) => match[1])),
)].sort();
if (!assets.some((asset) => asset.endsWith('.js')) || !assets.some((asset) => asset.endsWith('.css'))) {
  throw new Error('Vite output did not expose both hashed JavaScript and CSS for service-worker precaching.');
}

const shell = [
  '/',
  '/privacy/',
  '/terms/',
  '/archive-landscape.webp',
  '/mark.svg',
  '/fonts/instrument-sans-latin.woff2',
  '/fonts/ibm-plex-mono-latin-500.woff2',
  ...assets,
];
const version = createHash('sha256').update(JSON.stringify(shell)).digest('hex').slice(0, 12);
const worker = `/* Generated by scripts/build-sw.mjs. Do not edit dist/site/sw.js directly. */
const CACHE = 'photo-exit-manifest-${version}';
const SHELL = ${JSON.stringify(shell)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(SHELL))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => key.startsWith('photo-exit-manifest-') && key !== CACHE)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  const result = caches.match(event.request).then((cached) => {
    if (cached) return { response: cached, shouldCache: false };
    return fetch(event.request).then((response) => ({ response, shouldCache: response.ok }));
  });
  event.respondWith(result.then(({ response }) => response));
  event.waitUntil(result.then(({ response, shouldCache }) => {
    if (!shouldCache) return undefined;
    return caches.open(CACHE).then((cache) => cache.put(event.request, response.clone()));
  }).catch(() => undefined));
});
`;

await writeFile(resolve(siteRoot, 'sw.js'), worker);
console.log(`Generated versioned service worker ${version} with ${shell.length} precached URLs.`);
